pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

- script: |
    dotnet build -c $(buildConfiguration)
    dotnet publish -c $(buildConfiguration) -o $BUILD_ARTIFACTSTAGINGDIRECTORY