pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: 'release'
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
